# Use the official Node.js 22 image
FROM node:20 AS frontend

# Create a directory for the app
WORKDIR /app/frontend

# Copy package.json and package-lock.json
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY ./frontend .

# Expose the port the app runs on
EXPOSE 4000

# Start the app
CMD ["npm", "start"]